#!/usr/bin/env bash

# General
alias ll="ls -l"
alias la="ls -a"
alias cls="clear && ls"

# Ansible
alias apb="ansible-playbook"
alias adoc="ansible-doc"
alias acfg="ansible-config"
alias avlt="ansible-vault"
alias agal="ansible-galaxy"
alias alint="ansible-lint"

# Python
alias python="python3"
alias pypile="python3 -m py_compile"

# System
alias sl="systemctl"
alias jl="journalctl"

alias arsync="rsync -havuHP --stats"

# OSBuild Composer
alias ccli="composer-cli"
complete -F _composer_cli ccli
