%pre --interpreter=/usr/bin/bash --erroronfail --log=/tmp/ks-pre-disk.log
# ---------------------------------------------------------------------------
# Dynamic disk provisioning for anaconda kickstart (BASH version)
#
# Behaviour:
#   * Finds non-removable, non-USB, writable disks sized 500 GiB .. 2 TiB.
#   * Two candidates of EXACTLY equal size  -> RAID1 mirror across both.
#   * Otherwise                              -> smallest matched disk, no RAID.
#   * Zero candidates                        -> abort (via --erroronfail).
#   * All of root/home/scratch/var/tmp/log/etc. are FIXED-size logvols; the
#     remaining VG capacity (often most of the disk on a storage-role box)
#     is soaked up by a --grow logvol at /srv/storage.
#
# The main kickstart pulls the result in with:   %include /tmp/diskpart.ks
# ---------------------------------------------------------------------------

set -uo pipefail          # -e is intentionally OFF: the filter loop below
                          # relies on tests returning non-zero to `continue`.

MIN_BYTES=$((500 * 1024 ** 3))     # 500 GiB  hard lower bound
MAX_BYTES=$((2   * 1024 ** 4))     # 2   TiB  hard upper bound
INCLUDE=/tmp/diskpart.ks

# LUKS passphrase for the encrypted LVM physical volume (root/home/var/etc.).
# CHANGE THIS before building - it is baked in plaintext wherever this %pre
# script ends up (the generated kickstart, and the blueprint's TOML if
# embed_kickstart is used). See the caution note at the end of this reply.
LUKS_PASSPHRASE="REPLACE_WITH_A_REAL_PASSPHRASE"

log(){ echo "[disk-pre] $*"; }

# --- emitters --------------------------------------------------------------
# The logical-volume block is identical for both layouts, so factor it out.
emit_lvs(){
cat >> "$INCLUDE" <<'EOF'
volgroup os pv.01
logvol /                --vgname=os --name=root    --fstype=xfs  --size=102400
logvol /home            --vgname=os --name=home    --fstype=xfs  --size=102400
logvol /scratch         --vgname=os --name=scratch --fstype=xfs  --size=102400
logvol /tmp             --vgname=os --name=tmp     --fstype=xfs  --size=10240
logvol /var             --vgname=os --name=var     --fstype=xfs  --size=10240
logvol /var/tmp         --vgname=os --name=vartmp  --fstype=xfs  --size=10240
logvol /var/log         --vgname=os --name=varlog  --fstype=xfs  --size=10240
logvol /var/log/audit   --vgname=os --name=audit   --fstype=xfs  --size=10240
logvol /var/log/journal --vgname=os --name=journal --fstype=xfs  --size=10240
logvol /srv/storage     --vgname=os --name=storage --fstype=xfs  --grow --size=1
logvol swap             --vgname=os --name=swap    --fstype=swap --recommended
EOF
}

emit_single(){
  local d="$1"
  cat > "$INCLUDE" <<EOF
# generated by %pre : single disk /dev/$d
ignoredisk --only-use=$d
zerombr
clearpart --all --initlabel --drives=$d
part /boot/efi --fstype=efi   --size=512  --ondisk=$d --label=ESP
part /boot     --fstype=xfs   --size=2048 --ondisk=$d --label=BOOT
part pv.01     --fstype=lvmpv --grow --size=1 --ondisk=$d --encrypted --passphrase="$LUKS_PASSPHRASE"
EOF
  emit_lvs
  echo "bootloader --boot-drive=$d" >> "$INCLUDE"
}

emit_raid(){
  local a="$1" b="$2"
  cat > "$INCLUDE" <<EOF
# generated by %pre : RAID1 mirror /dev/$a + /dev/$b
ignoredisk --only-use=$a,$b
zerombr
clearpart --all --initlabel --drives=$a,$b
part raid.efi1  --fstype=raid --size=512  --ondisk=$a
part raid.efi2  --fstype=raid --size=512  --ondisk=$b
part raid.boot1 --fstype=raid --size=2048 --ondisk=$a
part raid.boot2 --fstype=raid --size=2048 --ondisk=$b
part raid.pv1   --fstype=raid --grow --size=1 --ondisk=$a
part raid.pv2   --fstype=raid --grow --size=1 --ondisk=$b
raid /boot/efi --fstype=efi   --level=1 --device=md0 raid.efi1 raid.efi2
raid /boot     --fstype=xfs   --level=1 --device=md1 raid.boot1 raid.boot2
raid pv.01     --fstype=lvmpv --level=1 --device=md2 --encrypted --passphrase="$LUKS_PASSPHRASE" raid.pv1 raid.pv2
EOF
  emit_lvs
  echo "bootloader --boot-drive=$a" >> "$INCLUDE"
}

# --- 1. collect candidate disks --------------------------------------------
# lsblk flags:  -d disks only  -n no header  -b bytes  -P key="value" pairs
#               -o pick columns.  -P avoids the "empty TRAN shifts fields" bug
#               you'd hit with plain column output.
declare -a CAND_NAME CAND_SIZE
while read -r line; do
    eval "$line"                          # sets NAME TYPE RM RO TRAN SIZE
    [ "$TYPE" = "disk" ]         || continue    # skip rom / loop / zram
    [ "$RM"   = "0" ]            || continue    # skip removable (USB stick, SD)
    [ "$RO"   = "0" ]            || continue    # skip read-only
    [ "$TRAN" = "usb" ]         && continue     # belt+suspenders: no USB HDDs
    [ "$SIZE" -ge "$MIN_BYTES" ] || continue
    [ "$SIZE" -le "$MAX_BYTES" ] || continue
    CAND_NAME+=("$NAME"); CAND_SIZE+=("$SIZE")
    log "candidate: $NAME size=$SIZE tran=${TRAN:-none}"
done < <(lsblk -dnb -P -o NAME,TYPE,RM,RO,TRAN,SIZE)

if [ "${#CAND_NAME[@]}" -eq 0 ]; then
    log "ERROR: no suitable disk (need non-removable, 500 GiB .. 2 TiB)."
    exit 1                                # --erroronfail halts the install
fi

# --- 2. sort candidates by size (ascending) --------------------------------
mapfile -t sorted < <(
    for i in "${!CAND_NAME[@]}"; do
        printf '%s %s\n' "${CAND_SIZE[$i]}" "${CAND_NAME[$i]}"
    done | sort -n
)
declare -a S_SIZE S_NAME
for row in "${sorted[@]}"; do
    S_SIZE+=("${row%% *}")                # size  = text before first space
    S_NAME+=("${row#* }")                 # name  = text after  first space
done
n=${#S_NAME[@]}

# --- 3. find the LARGEST equal-size pair (equal sizes sit adjacent) --------
pair_a=""; pair_b=""; pair_size=""
for (( i=n-1; i>=1; i-- )); do
    if [ "${S_SIZE[$i]}" -eq "${S_SIZE[$((i-1))]}" ]; then
        pair_a="${S_NAME[$((i-1))]}"; pair_b="${S_NAME[$i]}"
        pair_size="${S_SIZE[$i]}"
        break
    fi
done

# --- 4. decide + emit ------------------------------------------------------
if [ -n "$pair_a" ]; then
    log "RAID1 across $pair_a + $pair_b (size=$pair_size)"
    emit_raid "$pair_a" "$pair_b"
else
    d="${S_NAME[0]}"; s="${S_SIZE[0]}"    # smallest matched disk
    log "single disk $d (size=$s), no RAID"
    emit_single "$d"
fi
log "wrote $INCLUDE"
%end
