%pre --interpreter=/usr/bin/python3 --erroronfail --log=/tmp/ks-pre-disk.log
# ---------------------------------------------------------------------------
# Dynamic disk provisioning for anaconda kickstart (PYTHON version)
#
# Behaviour:
#   * Finds non-removable, non-USB, writable disks sized 500 GiB .. 2 TiB.
#   * Two candidates of EXACTLY equal size  -> RAID1 mirror across both.
#   * Otherwise                              -> smallest matched disk, no RAID.
#   * Zero candidates                        -> abort (via --erroronfail).
#
# The main kickstart pulls the result in with:   %include /tmp/diskpart.ks
# ---------------------------------------------------------------------------
import json
import subprocess
import sys

MIN_B  = 500 * 1024**3       # 500 GiB  hard lower bound
MAX_B  = 2   * 1024**4       # 2   TiB  hard upper bound
INCLUDE = "/tmp/diskpart.ks"

# LUKS passphrase for the encrypted LVM physical volume (root/home/var/etc.).
# CHANGE THIS before building - it is baked in plaintext wherever this %pre
# script ends up (the generated kickstart, and the blueprint's TOML if
# embed_kickstart is used). See the caution note at the end of this reply.
LUKS_PASSPHRASE = "REPLACE_WITH_A_REAL_PASSPHRASE"

# Data-driven LV table: (mountpoint, lv-name, size-in-MiB).
# Editing the layout is now editing this list, nothing else.
LVS = [
    ("/",                "root",    102400),
    ("/home",            "home",    102400),
    ("/scratch",         "scratch", 102400),
    ("/tmp",             "tmp",      10240),
    ("/var",             "var",      10240),
    ("/var/tmp",         "vartmp",   10240),
    ("/var/log",         "varlog",   10240),
    ("/var/log/audit",   "audit",    10240),
    ("/var/log/journal", "journal",  10240),
]


def log(msg):
    print("[disk-pre] %s" % msg)


def truthy(v):
    # lsblk reports rm/ro as booleans (new) or "0"/"1" (old); normalise both.
    return str(v).strip().lower() in ("1", "true")


def lv_lines():
    out = ["volgroup os pv.01"]
    for mount, name, size in LVS:
        out.append("logvol %-22s --vgname=os --name=%-8s --fstype=xfs  --size=%d"
                   % (mount, name, size))
    # Everything above is fixed-size; without a --grow logvol the rest of the
    # VG (often most of the disk, on a storage-role box) is left as unused
    # free space. This one soaks up whatever's left.
    out.append("logvol /srv/storage           --vgname=os --name=storage  "
               "--fstype=xfs  --grow --size=1")
    out.append("logvol swap                   --vgname=os --name=swap     "
               "--fstype=swap --recommended")
    return out


def single_layout(disk):
    return [
        "# generated by %%pre : single disk /dev/%s" % disk,
        "ignoredisk --only-use=%s" % disk,
        "zerombr",
        "clearpart --all --initlabel --drives=%s" % disk,
        "part /boot/efi --fstype=efi   --size=512  --ondisk=%s --label=ESP" % disk,
        "part /boot     --fstype=xfs   --size=2048 --ondisk=%s --label=BOOT" % disk,
        "part pv.01     --fstype=lvmpv --grow --size=1 --ondisk=%s --encrypted --passphrase=\"%s\""
        % (disk, LUKS_PASSPHRASE),
    ] + lv_lines() + ["bootloader --boot-drive=%s" % disk]


def raid_layout(a, b):
    return [
        "# generated by %%pre : RAID1 mirror /dev/%s + /dev/%s" % (a, b),
        "ignoredisk --only-use=%s,%s" % (a, b),
        "zerombr",
        "clearpart --all --initlabel --drives=%s,%s" % (a, b),
        "part raid.efi1  --fstype=raid --size=512  --ondisk=%s" % a,
        "part raid.efi2  --fstype=raid --size=512  --ondisk=%s" % b,
        "part raid.boot1 --fstype=raid --size=2048 --ondisk=%s" % a,
        "part raid.boot2 --fstype=raid --size=2048 --ondisk=%s" % b,
        "part raid.pv1   --fstype=raid --grow --size=1 --ondisk=%s" % a,
        "part raid.pv2   --fstype=raid --grow --size=1 --ondisk=%s" % b,
        "raid /boot/efi --fstype=efi   --level=1 --device=md0 raid.efi1 raid.efi2",
        "raid /boot     --fstype=xfs   --level=1 --device=md1 raid.boot1 raid.boot2",
        "raid pv.01     --fstype=lvmpv --level=1 --device=md2 --encrypted --passphrase=\"%s\" raid.pv1 raid.pv2"
        % LUKS_PASSPHRASE,
    ] + lv_lines() + ["bootloader --boot-drive=%s" % a]


# --- 1. collect candidate disks --------------------------------------------
# lsblk -J gives JSON; -d disks only; -b bytes; -o picks columns.
raw = subprocess.run(
    ["lsblk", "-db", "-J", "-o", "NAME,TYPE,RM,RO,TRAN,SIZE"],
    capture_output=True, text=True, check=True,
).stdout
devices = json.loads(raw)["blockdevices"]

candidates = []   # list of (size_bytes, name)
for d in devices:
    if d.get("type") != "disk":     continue    # skip rom / loop / zram
    if truthy(d.get("rm")):         continue    # skip removable
    if truthy(d.get("ro")):         continue    # skip read-only
    if d.get("tran") == "usb":      continue    # skip USB HDDs
    size = int(d["size"])
    if not (MIN_B <= size <= MAX_B):
        continue
    candidates.append((size, d["name"]))
    log("candidate: %s size=%d tran=%s" % (d["name"], size, d.get("tran")))

if not candidates:
    log("ERROR: no suitable disk (need non-removable, 500 GiB .. 2 TiB).")
    sys.exit(1)                                  # --erroronfail halts install

# --- 2. sort ascending, then find the LARGEST equal-size pair --------------
candidates.sort()                                # by size, then name
pair = None
for i in range(len(candidates) - 1, 0, -1):
    if candidates[i][0] == candidates[i - 1][0]:
        pair = (candidates[i - 1][1], candidates[i][1], candidates[i][0])
        break

# --- 3. decide + write -----------------------------------------------------
if pair:
    a, b, size = pair
    log("RAID1 across %s + %s (size=%d)" % (a, b, size))
    lines = raid_layout(a, b)
else:
    size, disk = candidates[0]                   # smallest matched disk
    log("single disk %s (size=%d), no RAID" % (disk, size))
    lines = single_layout(disk)

with open(INCLUDE, "w") as fh:
    fh.write("\n".join(lines) + "\n")
log("wrote %s" % INCLUDE)
%end
